[package]
name = "everest"
version = "0.1.0"
authors = [
    "Eduardo Leegwater Sim√µes <eduardo@dusk.network>",
]
edition = "2021"

license = "MPL-2.0"

[dependencies]
dallo = { path = "../../dallo", default-features = false }

[lib]
crate-type = ["cdylib", "rlib"]

[workspace]
