[package]
name = "counter"
version = "0.1.0"
authors = [
    "Kristoffer StrÃ¶m <kristoffer@dusk.network>",
]
edition = "2021"

[dependencies]
dallo = { path = "../../dallo", default-features = false }

[lib]
crate-type = ["cdylib", "rlib"]
