[workspace]
members = [
    "box",
    "c-example",
    "callcenter",
    "constructor",
    "counter",
    "debugger",
    "double_counter",
    "empty_constructor",
    "eventer",
    "everest",
    "fallible_counter",
    "feeder",
    "fibonacci",
    "grower",
    "host",
    "invalid",
    "merkle",
    "metadata",
    "micro",
    "crossover",
    "spender",
    "stack",
    "vector",
]
resolver = "2"
