[package]
name = "vector"
version = "0.1.0"
authors = [
    "Kristoffer Str√∂m <kristoffer@dusk.network>",
]
edition = "2021"

license = "MPL-2.0"

[dependencies]
piecrust-uplink = { path = "../../piecrust-uplink", features = ["abi", "dlmalloc"] }

[lib]
crate-type = ["cdylib", "rlib"]
